import type { Metadata } from "next";
import "./globals.scss";
import Navbar from "./components/Navbar";
import { UserProvider } from "./UserContext";

export const metadata: Metadata = {
  title: "Youtube Channel fetcher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
